---

- name: Make directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy files
  become: true
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Project files
  become: true
  shell: ls /home/ubuntu/backend
  args:
    executable: /bin/bash
  register: after_unarchiving

- name: Start App
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 logs
  args:
    executable: /bin/bash
  register: start_app_results

- name: Results after unarchiving
  debug:
    msg: "{{ after_unarchiving.stdout_lines }}"

- name: Show results after app starts
  debug:
    msg: "{{ start_app_results.stdout_lines }}"
  



