---

- name: Make directory
  become: true
  file:
    path: ~/project
    state: directory

- name: Copy files
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project

- name: Project files
  become: true
  shell: ls ~/project
  args:
    executable: /bin/bash
  register: after_unarchiving

- name: Start App
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    executable: /bin/bash
    chdir: ~/project
  register: start_app_results

- name: Results after unarchiving
  debug:
    msg: "{{ after_unarchiving.stdout_lines }}"

- name: Show results after app starts
  debug:
    msg: "{{ start_app_results.stdout_lines }}"
  



